apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gitlab-dev

resources:
  - ../../base

namespace: gitlab-dev

patches:
- path: storage-patch.yaml
- path: resources-patch.yaml

commonLabels:
  environment: dev

replicas:
- name: gitlab
  count: 1
- name: postgresql
  count: 1
- name: redis
  count: 1