apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gitlab-prod

bases:
  - ../../base

namespace: gitlab-prod

patchesStrategicMerge:
- storage-patch.yaml
- resources-patch.yaml
- replica-patch.yaml

labels:
  environment: prod

replicas:
- name: postgresql
  count: 1
- name: redis
  count: 1