apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gitlab-prod

resources:
- ../../base

namespace: gitlab-prod

commonLabels:
  environment: prod

replicas:
- name: gitlab
  count: 1
- name: postgresql
  count: 1
- name: redis
  count: 1